sonar.projectKey=boujuron
sonar.projectName=Boujuron Intelligence
sonar.projectVersion=1.0

sonar.sources=services
sonar.tests=tests

sonar.python.version=3.14

sonar.host.url=http://localhost:9000
sonar.token=YOUR_TOKEN